
export const SmobilpayErrorMessages: Record<string | number, string> = {
  0: "Aucune erreur détectée. La transaction est en cours ou déjà traitée avec succès.",
  2: "Transaction en cours d'investigation. Contactez le support.",
  3: "Transaction annulée. Contactez le support.",
  40401: "Plus de bons gratuits disponibles.",
  40701: "Timeout lors du paiement. Demandez un nouveau devis et réessayez.",
  41002: "Solde passerelle insuffisant. Réessayez plus tard.",
  41004: "Passerelle temporairement indisponible. Réessayez plus tard.",
  60001: "Session agent non ouverte. Contactez le support.",
  60003: "Session entreprise non ouverte. Contactez le support.",
  60010: "Affectation tiroir invalide. Contactez le support.",
  702000: "Erreur générale de paiement. Contactez le support.",
  702100: "Erreur communication avec fournisseur. Contactez le support si persiste.",
  702101: "Destination invalide. Vérifiez et corrigez la requête.",
  702102: "Montant inférieur au seuil acceptable. Vérifiez et corrigez.",
  702103: "Montant supérieur au seuil acceptable. Vérifiez et corrigez.",
  702105: "Timeout fournisseur. Vérifiez statut et agissez.",
  702106: "Fournisseur temporairement injoignable. Réessayez plus tard.",
  703000: "Erreur métier générale. Contactez le support.",
  703020: "Fournisseur injoignable après init. Réessayez plus tard.",
  703100: "Entrée invalide. Corrigez et réessayez.",
  703102: "Transaction rejetée par fournisseur. Réessayez ou contactez support.",
  703103: "Compte destinataire bloqué. Informez client.",
  703104: "Compte expéditeur bloqué. Informez client.",
  703105: "Destinataire inconnu. Informez client.",
  703106: "Expéditeur inconnu. Informez client.",
  703107: "Fonds insuffisants destinataire. Informez client.",
  703108: "Fonds insuffisants expéditeur. Informez client.",
  703109: "Montant inférieur seuil fournisseur. Corrigez et réessayez.",
  703110: "Montant supérieur seuil fournisseur. Corrigez et réessayez.",
  703111: "Limite dépassée expéditeur. Informez client.",
  703112: "Limite dépassée destinataire. Informez client.",
  703113: "Item de paiement non disponible ou déjà payé. Récupérez nouvel ID.",
  703114: "Montant rejeté par fournisseur. Corrigez et réessayez.",
  703117: "Numéro de compte non supporté. Informez client.",
  703201: "Confirmation client requise. Informez client.",
  703202: "Paiement rejeté par client. Informez et réessayez.",
  703203: "Identifiants approbation invalides. Informez et réessayez.",
  703401: "Transaction introuvable chez fournisseur. Contactez support.",
  703501: "Erreur technique validation paiement. Contactez support.",
  703503: "Maintenance fournisseur. Réessayez plus tard.",
  704000: "Erreur technique générale. Contactez support.",
  704003: "Erreur traitement paiement. Contactez support.",
  704004: "Temps expiré entre recherche et paiement. Recommencez.",
  704005: "Erreur technique validation paiement. Contactez support.",
  704006: "Réponse inconnue fournisseur. Contactez support.",
  705000: "Erreur technique inattendue. Contactez support.",
  705010: "Timeout communication fournisseur. Réessayez plus tard.",
  705020: "Timeout communication fournisseur. Réessayez plus tard.",
  705030: "Timeout communication fournisseur. Réessayez plus tard.",
  90000: "Erreur interne serveur. Réessayez plus tard ou contactez support.",
};

export function getSmobilpayErrorMessage(code: string | number): string {
  return SmobilpayErrorMessages[code] || "Une erreur inconnue est survenue lors de la transaction.";
}